name: Validate API Zoo PR

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'data/apizoo/**'

jobs:
  check-api-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for duplicate APIs
        id: check
        run: |
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d @data.json https://5472-23-93-94-38.ngrok-free.app/api/validate)
          echo "Server response: $RESPONSE"
          if [[ "$RESPONSE" == *"duplicate API"* ]]; then
            echo "::set-output name=duplicate::true"
          else
            echo "::set-output name=duplicate::false"
          fi
      
      - name: Fail if duplicate API
        if: steps.check.outputs.duplicate == 'true'
        run: |
          echo "Duplicate API detected, failing the workflow"
          exit 1
      
      - name: Comment on PR if duplicate API
        if: steps.check.outputs.duplicate == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: **Duplicate API detected**: This PR cannot be merged.
          token: ${{ secrets.GITHUB_TOKEN }}
