name: Validate API Zoo PR

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'data/apizoo/**'

jobs:
  check-api-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get list of changed files
        id: files
        uses: actions/github-script@v5
        with:
          script: |
            const result = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            const fileList = result.data.map(file => file.filename);
            core.setOutput('list', fileList.join('\n'));
      
      - name: Check for duplicate APIs
        id: check
        run: |
          FILES="${{ steps.files.outputs.list }}"
          for FILE in $FILES; do
            if [[ "$FILE" == "data/apizoo/"* ]]; then
              DATA=$(jq -c . < "$FILE")
              RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d "$DATA" https://5472-23-93-94-38.ngrok-free.app/api/validate)
              echo "Validation response for $FILE: $RESPONSE"
              if [[ "$RESPONSE" == *"\"duplicate\": true"* ]]; then
                echo "::set-output name=duplicate::true"
                break
              fi
            fi
          done
      
      - name: Fail if duplicate API
        if: steps.check.outputs.duplicate == 'true'
        run: |
          echo "Duplicate API detected, failing the workflow"
          exit 1
      
      - name: Comment on PR if duplicate API
        if: steps.check.outputs.duplicate == 'true'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: **Duplicate API detected**: This PR cannot be merged.
          token: ${{ secrets.GITHUB_TOKEN }}
